# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base    = ""
  publish = "build/"
  command = "CI='' npm run build"
  functions= "functions/"

[[redirects]]
  from = "/*"
  to = "public/index.html"
  status = 200